name: Check vatiables

on:
  push:
    branches:
      - main
        
jobs:
  run-postman-collection:
    runs-on: ubuntu-latest   
    environment: qauto

    steps:      
       # Шаг 111: Установить HTML reporter
      - name: adssads
        run: echo " My ${{ vars.URL }}"
        
      
